"""
P3 — Rule Validation

Runs a candidate Rule (usually AI-generated by P1) against held-out raw
log lines it was NOT built from, and reports whether it's safe to show to
a human reviewer (P4) at all. This does not replace human review — it's a
cheap, deterministic first pass that catches obviously broken rules
before wasting a reviewer's time on them.
"""
import re

from schemas.schemas import Rule, ValidationResult

# Deliberately simple — good enough to catch "this obviously isn't an IP",
# not meant to validate every edge case of real-world IP formatting.
_IP_PATTERN = re.compile(r"^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$")

# Mirrors parser_engine/apply_rule.py's _parse_extension_kv exactly. Kept
# as a duplicate (not imported) so P3's validation logic has no runtime
# dependency on P2's module — but the regex itself MUST stay identical to
# theirs, since we're validating rules against the same interpretation
# P2 will actually use when applying them for real.
_EXTENSION_KV_PATTERN = re.compile(r'(\w+)=(?:"([^"]*)"|([^=]+?)(?=\s+\w+=|$))')


def _parse_extension_kv(extension_str: str) -> dict[str, str]:
    """Parse key=value pairs out of a CEF-style extension blob, e.g.
    'src=1.2.3.4 dst=5.6.7.8 msg=Suspicious DNS Query' ->
    {'src': '1.2.3.4', 'dst': '5.6.7.8', 'msg': 'Suspicious DNS Query'}
    """
    pairs: dict[str, str] = {}
    if not extension_str:
        return pairs
    for match in _EXTENSION_KV_PATTERN.finditer(extension_str):
        key = match.group(1)
        value = match.group(2) if match.group(2) is not None else match.group(3)
        pairs[key] = value.strip()
    return pairs


def _extract_fields(pattern_match: re.Match, has_extension_group: bool) -> dict[str, str]:
    """
    Merge a rule's directly-named capture groups with any fields hiding
    inside an 'extension' blob group, so downstream checks don't care
    which style the rule uses.
    """
    fields = dict(pattern_match.groupdict())
    if has_extension_group:
        extension_text = fields.get("extension")
        if extension_text:
            fields.update(_parse_extension_kv(extension_text))
    return fields


def validate_rule(rule: Rule, held_out_lines: list[str]) -> ValidationResult:
    """
    Run rule.pattern against held_out_lines (raw log lines NOT used to
    generate the rule). passed is True only if every check below passes
    on every held-out line.
    """
    notes: list[str] = []

    if not held_out_lines:
        return ValidationResult(
            rule_fingerprint_id=rule.fingerprint_id,
            passed=False,
            checks={
                "pattern_matches_all_lines": False,
                "ip_fields_look_like_ips": False,
                "port_fields_look_like_ports": False,
                "no_orphan_mappings": False,
            },
            notes="No held_out_lines were provided — cannot validate a rule against nothing.",
        )

    try:
        compiled = re.compile(rule.pattern)
    except re.error as e:
        return ValidationResult(
            rule_fingerprint_id=rule.fingerprint_id,
            passed=False,
            checks={
                "pattern_matches_all_lines": False,
                "ip_fields_look_like_ips": False,
                "port_fields_look_like_ports": False,
                "no_orphan_mappings": False,
            },
            notes=f"Rule pattern does not even compile as a regex: {e}",
        )

    named_groups = set(compiled.groupindex.keys())
    has_extension_group = "extension" in named_groups

    # The remaining checks run per held-out line, and must hold on EVERY
    # line for the overall check to pass. Orphan-mapping detection is
    # dynamic when an 'extension' group is present, since a mapped field
    # like "src" may legitimately live inside that blob rather than as
    # its own named group — we only know for sure after actually parsing
    # each line, so we track every field name ever produced across all
    # lines and compare mappings against that at the end.
    pattern_matches_all_lines = True
    ip_fields_look_like_ips = True
    port_fields_look_like_ports = True
    fields_seen_anywhere: set[str] = set(named_groups)

    for i, line in enumerate(held_out_lines):
        match = compiled.search(line)
        if match is None:
            pattern_matches_all_lines = False
            notes.append(f"Line {i}: pattern did not match at all — {line!r}")
            continue  # can't check field values on a line that didn't match

        fields = _extract_fields(match, has_extension_group)
        fields_seen_anywhere.update(fields.keys())

        for fm in rule.field_mappings:
            value = fields.get(fm.source_field)
            path_lower = fm.ocsf_path.lower()

            if "ip" in path_lower:
                if value is None or not _IP_PATTERN.match(value):
                    ip_fields_look_like_ips = False
                    notes.append(
                        f"Line {i}: field '{fm.source_field}' -> {fm.ocsf_path} "
                        f"does not look like an IP (captured {value!r})."
                    )

            if "port" in path_lower:
                is_valid_port = False
                if value is not None and value.isdigit():
                    port_num = int(value)
                    is_valid_port = 0 <= port_num <= 65535
                if not is_valid_port:
                    port_fields_look_like_ports = False
                    notes.append(
                        f"Line {i}: field '{fm.source_field}' -> {fm.ocsf_path} "
                        f"is not a valid port 0-65535 (captured {value!r})."
                    )

    # A mapping is a true orphan only if its source_field never showed up
    # anywhere — not as a named group, and not inside any parsed
    # extension blob across every held-out line.
    orphan_fields = [
        fm.source_field
        for fm in rule.field_mappings
        if fm.source_field not in fields_seen_anywhere
    ]
    no_orphan_mappings = len(orphan_fields) == 0
    if not no_orphan_mappings:
        notes.append(
            f"Orphan field_mappings (never captured, directly or via extension parsing): {orphan_fields}."
        )

    checks = {
        "pattern_matches_all_lines": pattern_matches_all_lines,
        "ip_fields_look_like_ips": ip_fields_look_like_ips,
        "port_fields_look_like_ports": port_fields_look_like_ports,
        "no_orphan_mappings": no_orphan_mappings,
    }

    passed = all(checks.values())
    final_notes = " | ".join(notes) if notes else "All checks passed on all held-out lines."

    return ValidationResult(
        rule_fingerprint_id=rule.fingerprint_id,
        passed=passed,
        checks=checks,
        notes=final_notes,
    )
