#!/usr/bin/env python3
"""Fragmentation bench for ulpf-core fingerprinting (spec §9, M1).

For every golden corpus (libs/ulpf-core/tests/data/golden/raw_logs_*.txt):

1. Fingerprint every line and group by ``fingerprint_id``. A known-format
   group whose lines do not all share one shape hash is a fragmentation.
2. Generate 100 mutated lines per corpus. Mutations randomize timestamps,
   IPs, ports (``IP:port``, ``key=value`` and JSON numeric fields), hostnames
   (``h####``) and free-text message word counts — exactly the values that
   vary between real events of the same format.
3. A mutant is stable iff it keeps its base line's fingerprint (known formats)
   and its base line's shape hash. Report per-corpus distinct shape hashes
   and the mutation-stability ratio.

Exit status: 0 if every known-format group is fragmentation-free and fully
mutation-stable, 1 otherwise. (``auto_`` groups cannot fragment by
construction: the provisional id is derived from the shape hash itself.)

Run from the repo root:  python bench/fingerprint_fragmentation.py
Writes: docs/m1-fragmentation.md
"""

from __future__ import annotations

import random
import sys
from pathlib import Path

from ulpf_core.fingerprint import fingerprint_id, shape_hash
from ulpf_core.mutations import mutate_line

ROOT = Path(__file__).resolve().parents[1]
GOLDEN = ROOT / "libs" / "ulpf-core" / "tests" / "data" / "golden"
DOC = ROOT / "docs" / "m1-fragmentation.md"

SEED = 20260919
MUTATIONS = 100

# Mutation machinery (regexes, rand helpers, WORDS, mutate_line) lives in
# ulpf_core.mutations since M2 — single definition shared with the candidate
# probe. The bench passes vary_text=True to keep its historical behavior
# (free-text message word counts are mutated too).


def run_bench(mutations: int = MUTATIONS, seed: int = SEED) -> dict:
    rng = random.Random(seed)
    corpora = sorted(GOLDEN.glob("raw_logs_*.txt"))
    if not corpora:
        raise SystemExit(f"no golden corpora found under {GOLDEN}")

    report: dict = {"seed": seed, "mutations": mutations, "corpora": [], "passed": True}
    for path in corpora:
        lines = [l for l in path.read_text(encoding="utf-8").splitlines() if l.strip()]
        groups: dict[str, list[str]] = {}
        for line in lines:
            groups.setdefault(fingerprint_id(line), []).append(line)

        group_rows = []
        for fp in sorted(groups):
            hashes = {shape_hash(l) for l in groups[fp]}
            known = not fp.startswith("auto_")
            fragmented = known and len(hashes) > 1
            group_rows.append({
                "fingerprint": fp,
                "lines": len(groups[fp]),
                "distinct_hashes": len(hashes),
                "fragmented": fragmented,
            })

        canonical = {fp: shape_hash(ls[0]) for fp, ls in groups.items()}
        mutant_hashes: set[str] = set()
        stable = 0
        failures: list[str] = []
        for _ in range(mutations):
            base = rng.choice(lines)
            fp = fingerprint_id(base)
            mutant = mutate_line(base, rng, vary_text=True)
            mutant_hashes.add(shape_hash(mutant))
            ok = shape_hash(mutant) == canonical[fp]
            if not fp.startswith("auto_"):
                ok = ok and fingerprint_id(mutant) == fp
            if ok:
                stable += 1
            elif not fp.startswith("auto_"):
                failures.append(
                    f"[{path.name}] {fp} mutant unstable:\n"
                    f"    base:   {base}\n    mutant: {mutant}"
                )

        known_failure = any(r["fragmented"] for r in group_rows) or bool(failures)
        report["passed"] &= not known_failure
        report["corpora"].append({
            "name": path.name,
            "lines": len(lines),
            "groups": group_rows,
            "group_count": len(groups),
            "distinct_line_hashes": len({shape_hash(l) for l in lines}),
            "distinct_mutant_hashes": len(mutant_hashes),
            "stability": stable / mutations,
            "failed": known_failure,
            "failures": failures,
        })
    return report


def write_doc(report: dict) -> None:
    out: list[str] = [
        "# M1 fragmentation bench (spec §9)",
        "",
        (
            f"Generated by `python bench/fingerprint_fragmentation.py` "
            f"(seed {report['seed']}, {report['mutations']} mutants per corpus). "
            "Do not edit by hand; re-run to regenerate."
        ),
        "",
        "## Method",
        "",
        "- Golden corpora live in `libs/ulpf-core/tests/data/golden/raw_logs_*.txt`.",
        "- Lines are grouped by `fingerprint_id`; every line in a group must share",
        "  one shape hash (the CEF corpus intentionally holds 3 vendor groups).",
        "- Each corpus also gets 100 mutants with randomized timestamps, IPs, ports,",
        "  hostnames (`h####`) and message word counts. A mutant is stable iff it",
        "  keeps its base line's fingerprint (known formats) and shape hash.",
        "- Exit is non-zero if any known-format group fragments or loses a mutant",
        "  (`auto_` groups cannot fragment by construction: id = shape hash).",
        "",
        "## Results",
        "",
        "| corpus | lines | fingerprint groups | distinct line shape hashes | distinct mutant shape hashes | mutation stability | result |",
        "|---|---:|---:|---:|---:|---:|---|",
    ]
    for corpus in report["corpora"]:
        out.append(
            f"| {corpus['name']} | {corpus['lines']} | {corpus['group_count']} "
            f"| {corpus['distinct_line_hashes']} | {corpus['distinct_mutant_hashes']} "
            f"| {corpus['stability']:.0%} | {'FAIL' if corpus['failed'] else 'PASS'} |"
        )
    out += ["", "## Per fingerprint group", "",
            "| corpus | fingerprint_id | lines | distinct shape hashes | result |",
            "|---|---|---:|---:|---|"]
    for corpus in report["corpora"]:
        for row in corpus["groups"]:
            out.append(
                f"| {corpus['name']} | `{row['fingerprint']}` | {row['lines']} "
                f"| {row['distinct_hashes']} | {'FAIL' if row['fragmented'] else 'PASS'} |"
            )
    out += [
        "",
        "## Reading the numbers",
        "",
        "- `distinct line shape hashes == fingerprint groups` means the golden lines",
        "  do not fragment within any format.",
        "- `mutation stability 100%` means no realistic value mutation changes a",
        "  line's shape — the property drift detection (later milestones) relies on.",
        "",
    ]
    DOC.write_text("\n".join(out), encoding="utf-8")


def main() -> int:
    report = run_bench()
    write_doc(report)

    print(f"seed={report['seed']} mutants/corpus={report['mutations']}")
    for corpus in report["corpora"]:
        status = "FAIL" if corpus["failed"] else "PASS"
        print(
            f"{corpus['name']:<28} lines={corpus['lines']:<3} "
            f"groups={corpus['group_count']} "
            f"line_hashes={corpus['distinct_line_hashes']} "
            f"mutant_hashes={corpus['distinct_mutant_hashes']} "
            f"stability={corpus['stability']:.0%} {status}"
        )
        for failure in corpus["failures"]:
            print(failure)
    print(f"wrote {DOC.relative_to(ROOT)}")
    print("RESULT:", "PASS" if report["passed"] else "FAIL")
    return 0 if report["passed"] else 1


if __name__ == "__main__":
    sys.exit(main())
